security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database: # 👈 Permet de charger les utilisateurs
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            user_checker: App\Security\UserEnabledChecker
            lazy: true
            provider: users_in_database  # 👈 Utilise la BDD à la place de "users_in_memory"
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home  # Chemin de redirection après la connexion

            logout:  
                path: app_logout
                target: app_home  # Chemin de redirection après la déconnexion

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # 👈 Sécurise la page Admin 
        - { path: ^/shop, roles: [ROLE_USER, ROLE_ADMIN] } # 👈 Securise la page boutique

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

