security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database: # 👈 Charger les utilisateurs depuis la BDD
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database  # 👈 Utiliser la BDD au lieu de "users_in_memory"
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home  # ✅ Redirection après connexion

            logout:  # 👈 Permettre la déconnexion
                path: app_logout
                target: app_home  # ✅ Rediriger après déconnexion

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # 👈 Protège la section admin
        - { path: ^/profile, roles: ROLE_USER }  # 👈 Protège le profil utilisateur

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

