security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database: # 👈 Load the Users
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            user_checker: App\Security\UserEnabledChecker
            lazy: true
            provider: users_in_database  # 👈 Use the Database instead of "users_in_memory"
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home  # ✅ Target path after log in

            logout:  # 👈 Logout
                path: app_logout
                target: app_home  # ✅ Target path after log out

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # 👈 Secure admin page
        - { path: ^/shop, roles: ROLE_USER } # 👈 Secure shop page

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

